url: http://w4p.be

# Site settings
title: W4P Crowdsourcing platform
email: pieterjan@openknowledge.be
description: "W4P is a crowdsourcingplatform that you can host yourself. Boost local / social / open innovation today!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 42cfd2
  secondary: 42cfd2
  secondary-dark: 2a3249

# Team names, titles and social links
people:
- name: Open Knowledge Belgium vzw
  pic: 1
  position: Project lead
  social:
    - title: desktop
      url: http://www.openknowledge.be/
    - title: twitter
      url: https://twitter.com/openknowledgebe
    - title: envelope
      url: mailto:pieterjan [at] openknowledge.be

- name: iDrops vzw
  pic: 2
  position: Pilot lead
  social:
    - title: desktop
      url: http://idrops.be/
    - title: twitter
      url: https://twitter.com/idropslabs
    - title: envelope
      url: mailto:bart.cornille [at] idrops.be

- name: Underlined
  pic: 3
  position: Technical Lead
  social:
    - title: desktop
      url: https://underlined.be/
    - title: twitter
      url: https://twitter.com/underlined_be
    - title: envelope
      url: mailto:michiel [at] underlined.be

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/openknowledgebe/W4P

# Postal address (add as many lines as necessary)
address:
  - line: Sint-Salvatorstraat 18/101
  - line: 9000, Ghent

# Build settings
markdown: kramdown
permalink: pretty
